### PR TITLE
getTime() added

### PR DESCRIPTION
**Pull request by krisnarocks**
int getTime(string args);

usage: getTime("year");

Will return the current year in int. Currently, it can only retun the year. Others need char to int conversion.

### CODE REVIEW

**Comment by raphydaphy** [comment]
:+2: for labels

**Comment by raphydaphy** [comment]
Best milestone ever ..

**Comment by plankp** [comment]
There is char to int

**Comment by plankp** [comment]
its in charUtils
`ctoi [0-9a-zA-Z+/] -> 0-63`
`ntoi [0-9] -> 0-9`

**Pull request merged**
