### PR TITLE
Added Makefile, fixed uninitialized string, improved keyboard input reading, and other small changes

### PR DESCRIPTION
**Pull request by Barteks2x**
Removed some useless variables, defined bool type (and used it everywhere I could find), and possibly other changed I forgot about.

### CODE REVIEW

**Comment by plankp** [comment]
Thank you for the Makefile. I needed that!

**Comment by Barteks2x** [comment]
Ooops, I forgot to add *.d file type to gitignore. These files shouldn't be there.

**Comment by plankp** [comment]
Can you also add the genInitrd image in?

**Comment by Barteks2x** [comment]
to makefile?

**Comment by plankp** [comment]
Yeah. I'm really bad with makefiles but is it possible to automate the `initrd.img` generation and copying?

**Comment by Barteks2x** [comment]
I can try to do that.

**Comment by plankp** [comment]
thanks

**Pull request merged**
