### PR TITLE
Fixed Makefile bugs

### PR DESCRIPTION
**Pull request by plankp**

### CODE REVIEW

**Comment by Barteks2x** [comment]
What was wrong with it?

**Comment by plankp** [comment]
Caps continues when shift or caps is disabled

**Comment by plankp** [comment]
During typing you know?

**Comment by Barteks2x** [comment]
Fixed it

**Comment by Barteks2x** [comment]
But I still don't know what was wrong with makefile

**Comment by plankp** [comment]
Bug is not the exact term

**Comment by plankp** [comment]
but it would not delete kernel.o, and files that end with .ao

**Pull request merged**
